fix(qa): ensure test report is produced when tests fail

diff --git a/.github/workflows/job.module-qa.yml b/.github/workflows/job.module-qa.yml
--- a/.github/workflows/job.module-qa.yml
+++ b/.github/workflows/job.module-qa.yml
@@ -74,31 +74,14 @@ jobs:
     steps:
       - name: checkout
         uses: actions/checkout@v4
-      
+
       - name: 'setup: go ${{ needs.module-info.outputs.goVersion }}'
         uses: actions/setup-go@v5
         with:
           go-version: ${{ needs.module-info.outputs.goVersion }}
           cache: false   # avoid "file exists" errors from tar: https://github.com/actions/setup-go/issues/403
-        
-      - name: 'go: lint'
-        if: ${{ github.ref != 'refs/heads/master' }}
-        uses: golangci/golangci-lint-action@v4
-        with:
-          version: latest
 
-      - name: 'go: test'
-        run: |
-          go mod download
-          go test -v -coverprofile=coverprofile ./... -json > test-run.json
-          
-      - name: 'artifact: upload [coverprofile]'
-        uses: actions/upload-artifact@v4
-        with:
-          name: coverprofile
-          path: coverprofile
-        
-      - name: 'go: test-report'
+      - name: 'setup: test-report'
         run: |
           # a script to download and run blugnu/test-report
 
@@ -114,24 +97,47 @@ jobs:
           # download test-report from blugnu/test-report/releases
           curl -LO https://github.com/blugnu/test-report/releases/download/v${ver}/test-report_${ver}_linux_amd64.tar.gz
           tar -xvzf test-report_${ver}_linux_amd64.tar.gz test-report
+          rm test-report_${ver}_linux_amd64.tar.gz
           
           if [[ ! -f "test-report" ]]; then
-            echo "::warning::test-report could not be installed; skipping test report"
+            echo "::warning::test-report could not be installed"
             exit 0
           else
             echo "::group::test-report version"
               ./test-report version
             echo "::endgroup::"
           fi
+    
+      - name: 'go: lint'
+        if: ${{ github.ref != 'refs/heads/master' }}
+        uses: golangci/golangci-lint-action@v4
+        with:
+          version: latest
 
-          cat test-run.json | ./test-report --title "Test Report"
+      - name: 'go: test'
+        run: |
+          go mod download
 
-          # add test report to the job summary
-          report=$(cat test-report.md)
-          echo -e "$report\n" >> $GITHUB_STEP_SUMMARY
+          if [[ -f test-report ]]; then
+            result=$((go test ./... -json | ./test-report) && echo "PASS" || echo "FAIL")
+            
+            # add test report to the job summary
+            report=$(cat test-report.md)
+            echo -e "$report\n" >> $GITHUB_STEP_SUMMARY
 
-          # remove the test-report binary and downloaded tar.gz
-          rm test-report test-report_${ver}_linux_amd64.tar.gz
+            if [[ "$result" == "FAIL" ]]; then
+              echo "::error::tests failed"
+              exit 1
+            fi
+          else
+            go test -v -coverprofile=coverprofile ./...
+          fi
+
+      - name: 'artifact: upload [coverprofile]'
+        uses: actions/upload-artifact@v4
+        with:
+          name: coverprofile
+          path: coverprofile
 
   coveralls:
     if: ${{ (github.ref == 'refs/heads/master') && (needs.qa.outputs.isPublic == 'true') && (needs.gitlog.outputs.isTagged == 'false') }}
