fix(qa): add -v flag when running tests
this fixes an issue in some tests where running with the -json
flag results in additional newlines in test output which in turn
can cause meta-tests (tests of tests) to fail

diff --git a/.github/workflows/job.module-qa.yml b/.github/workflows/job.module-qa.yml
--- a/.github/workflows/job.module-qa.yml
+++ b/.github/workflows/job.module-qa.yml
@@ -108,7 +108,7 @@ jobs:
           go mod download
 
           if [[ -f test-report ]]; then
-            result=$((go test ./... -coverprofile=coverprofile -json | ./test-report) && echo "PASS" || echo "FAIL")
+            result=$((go test ./... -coverprofile=coverprofile -v -json | ./test-report) && echo "PASS" || echo "FAIL")
             
             # add test report to the job summary
             report=$(cat test-report.md)
